version: "3.7"

services:
  api:
    build:
      context: src
      target: base
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    environment:
      - PORT=${PORT}
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - container-network
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev

  db:
    image: mysql:8
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - container-network
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  container-network:
    driver: bridge
