version: "3.7"

services:
  api:
    build:
      context: src
      target: base
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
